version: "3"

services:
  web:
    build: ./docker/config/nginx/main
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
    networks:
      - internal

  main-app:
    build: 
      context: ./docker/config/php
    volumes:
      - .:/var/www/html
    networks:
      - internal

  login-web-server:
    build: ./docker/config/nginx/login
    ports:
      - 8001:80
    volumes:
      - ./applications/app-login:/var/www/html
    networks:
      - internal

  login-app:
    build: ./docker/config/php
    volumes:
      - ./applications/app-login:/var/www/html
    networks:
      - internal

  catalog-web-server:
    build: ./docker/config/nginx/catalog
    ports:
      - 8002:80
    volumes:
      - ./applications/app-catalog:/var/www/html
    networks:
      - internal

  header-server:
    build: ./docker/config/nginx/header
    ports:
      - 8003:80
    volumes:
      - ./applications/app-header:/var/www/html
    networks:
      - internal

  footer-server:
    build: ./docker/config/nginx/header
    ports:
      - 8004:80
    volumes:
      - ./applications/app-footer:/var/www/html
    networks:
      - internal


  catalog-app:
    build: ./docker/config/php
    volumes:
      - ./applications/app-catalog:/var/www/html
    networks:
      - internal

networks:
  internal:
    driver: bridge
