parameters:
    servers:
        header:
            url: 'http://header-server'
            assetsPrefix: header
        footer:
            url: 'http://footer-server'
            assetsPrefix: footer
        login:
            url: 'http://login-web-server'
            assetsPrefix: login
        catalog:
            url: 'http://catalog-web-server'
            assetsPrefix: catalog

services:
