parameters:
    servers:
        header: 'http://header-server'
        footer: 'http://footer-server'
        login: 'http://login-web-server'
        catalog: 'http://catalog-web-server'

services:
